apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.Provisioner.Name }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  file.system.id: {{ .Values.Provisioner.EfsId }}
  aws.region: {{ .Values.Provisioner.Region }}
  provisioner.name: {{ .Values.Provisioner.ClassName }}
