apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ .Chart.Name }}
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    provider: "devopskube"
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - secretName: {{ .Chart.Name }}-tls
    hosts:
    - {{ .Values.hostName }}
  rules:
  - host: {{ .Values.hostName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: 80
