apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-flink-config
  labels:
    app: {{ template "fullname" . }}
data:
  flink-conf.yaml: |
{{- if .Values.flink.persistent_volume_claim.enabled }}
    jobmanager.web.upload.dir: {{ .Values.flink.persistent_volume_claim.mountdir }}
{{- end }}
    blob.server.port: 6124
    jobmanager.rpc.address: {{ template "fullname" . }}-jobmanager.{{ .Release.Namespace }}.svc.cluster.local
    jobmanager.rpc.port: 6123
    jobmanager.heap.mb: {{ .Values.flink.jobmanager_heap_mb }}
    taskmanager.heap.mb: {{ .Values.flink.taskmanager_heap_mb }}
    taskmanager.numberOfTaskSlots: {{ .Values.flink.num_slots_per_taskmanager }}
{{- if .Values.flink.highavailability.enabled }}
    fs.hdfs.hadoopconf: /etc/hadoop/conf
    high-availability: zookeeper
    high-availability.jobmanager.port: 6123
    high-availability.zookeeper.quorum: {{ .Values.flink.highavailability.zookeeper_quorum }}
    high-availability.cluster-id: {{ template "fullname" . }}
    high-availability.storageDir: s3a://{{ .Values.flink.highavailability.state_s3_bucket }}/{{ template "fullname" . }}
{{- end }}
  log4j.properties: |
{{.Files.Get "config/log4j.properties" | indent 4}}
  logback.xml: |
{{.Files.Get "config/logback.xml" | indent 4}}
  log4j-console.properties: |
{{.Files.Get "config/log4j-console.properties" | indent 4}}
  log4j-cli.properties: |
{{.Files.Get "config/log4j-cli.properties" | indent 4}}
