kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: efs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: efs-provisioner
    spec:
      containers:
        - name: efs-provisioner
          image: quay.io/external_storage/efs-provisioner:latest
          env:
            - name: FILE_SYSTEM_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.Provisioner.ConfigName }}
                  key: file.system.id
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.Provisioner.ConfigName }}
                  key: aws.region
            - name: PROVISIONER_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.Provisioner.ConfigName }}
                  key: provisioner.name
          volumeMounts:
            - name: pv-volume
              mountPath: {{ .Values.Persistence.MountPath }}
      volumes:
        - name: pv-volume
          nfs:
            server: {{ .Values.Persistence.Server }}
            path: /
