kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Values.Provisioner.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.Provisioner.Name }}
    spec:
      containers:
        - name: efs-provisioner
          image: quay.io/external_storage/efs-provisioner:latest
          env:
            - name: FILE_SYSTEM_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.Provisioner.Name }}
                  key: file.system.id
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.Provisioner.Name }}
                  key: aws.region
            - name: PROVISIONER_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.Provisioner.Name }}
                  key: provisioner.name
          volumeMounts:
            - name: pv-volume
              mountPath: {{ .Values.Persistence.MountPath }}
      volumes:
        - name: pv-volume
          nfs:
            server: {{ template "efsdns" . }}
            path: /
#
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
# {{- if .Values.RBAC.Enabled -}}
# kind: ClusterRoleBinding
# apiVersion: rbac.authorization.k8s.io/v1beta1
# metadata:
#  name: adminbinding
#  namespace: {{ .Release.Namespace }}
# subjects:
# - kind: ServiceAccount
#  name: {{ .Values.RBAC.ServiceAccount }}
#  namespace: {{ .Release.Namespace }}
# roleRef:
#  kind: ClusterRole
#  name: {{ .Values.RBAC.RoleName }}
#  apiGroup: rbac.authorization.k8s.io
# {{- end }}
