
RBAC:
  Enabled: true
  RoleName: cluster-admin
  ServiceAccount: default

Provisioner:
  EfsId: fs-922ba2db
  Region: us-east-1
  Name: efs-provisioner
  ClassName: example.com/aws-efs


Persistence:
  Enabled: true
  AccessMode: ReadWriteMany
  StorageClass: aws-efs
  Size: 50Gi
  MountPath: /persistentvolumes
  ClaimName: efs
  ExistingClaim: false
