
Provisioner:
  EfsId: fs-b825a3f1
  Region: us-east-1
  Name: tools.aws.com.br/aws-efs
  ConfigName: efs-provisioner


Persistence:
  Enabled: true
  AccessMode: ReadWriteOnce
  StorageClass: slow
  Size: 10Gi
  MountPath: /persistentvolumes
  Server: fs-b825a3f1.efs.us-east-1.amazonaws.com
