
RBAC:
  Enabled: true
  RoleName: cluster-admin
  ServiceAccount: default

Provisioner:
  EfsId: fs-5cb2f815
  Region: us-east-1
  Name: efs-provisioner
  ClassName: tools.aws.com.br/aws-efs


Persistence:
  Enabled: true
  AccessMode: ReadWriteMany
  StorageClass: efs-slow
  Size: 50Gi
  MountPath: /persistentvolumes
  ExistingClaim: false
