
RBAC:
  Enabled: true
  RoleName: cluster-admin
  ServiceAccount: default

Provisioner:
  EfsId: fs-71155e38
  Region: us-east-1
  Name: efs-provisioner
  ClassName: tools.aws.com.br/aws-efs


Persistence:
  Enabled: true
  AccessMode: ReadWriteMany
  StorageClass: slow
  Size: 10Gi
  MountPath: /persistentvolumes
