images:
  flink: flink:1.3.2-hadoop27-scala_2.11
  additional_classpath_files: docker.io/plucas/additional-flink-jars:latest

resources:
  jobmanager:
    limits:
      cpu: 500m
      memory: 1280Mi
    requests:
      cpu: 500m
      memory: 1280Mi
  taskmanager:
    limits:
      memory: 1280Mi
    requests:
      memory: 1280Mi

flink:
  jobmanager_heap_mb: 1024
  taskmanager_heap_mb: 1024
  num_taskmanagers: 2
  num_slots_per_taskmanager: 1
  persistent_volume_claim:
    enabled: false
    claimName: omo-flink-fs-aws-efs
    mountdir: /persistentvolumes

  highavailability:
    enabled: false
#    zookeeper_quorum: zookeeper-zookeeper-0.omo-dev.svc.cluster,zookeeper-zookeeper-1.omo-dev.svc.cluster,zookeeper-zookeeper-2.omo-dev.svc.cluster
    zookeeper_quorum: zookeeper-zookeeper.omo-dev.svc.cluster.local
    state_s3_bucket: br-com-ihm-kubernetes-zk-qa
    aws_access_key_id: AKIAISLAFJE2RXHZ4AIA
    aws_secret_access_key: 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
